// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_LHucHiPBgXYj0LzX2c-3llKIbuk-wQc',
    appId: '1:1042386127646:web:c4d7d980aee8009a27170f',
    messagingSenderId: '1042386127646',
    projectId: 'socialloginapp-ab8cf',
    authDomain: 'socialloginapp-ab8cf.firebaseapp.com',
    storageBucket: 'socialloginapp-ab8cf.appspot.com',
    measurementId: 'G-LHFT7F5GY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVROTL9MgmbPiEGGBPLNNtXHPXKdgADw',
    appId: '1:1042386127646:android:8f4253a76b5ccc4f27170f',
    messagingSenderId: '1042386127646',
    projectId: 'socialloginapp-ab8cf',
    storageBucket: 'socialloginapp-ab8cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzLz-kXAZExRwawW8M5sMADvWKZo8zw4M',
    appId: '1:1042386127646:ios:c9189c6a99c2adfb27170f',
    messagingSenderId: '1042386127646',
    projectId: 'socialloginapp-ab8cf',
    storageBucket: 'socialloginapp-ab8cf.appspot.com',
    iosClientId: '1042386127646-g8gkf807dk1hqjp2sdn3s7oqbfbpb0nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialautologin',
  );
}
